package com.calorielog.module.training.plan.service;

import com.calorielog.common.exception.BizException;
import com.calorielog.common.exception.ErrorCode;
import com.calorielog.module.training.plan.dto.SavePlanRequest;
import com.calorielog.module.training.plan.dto.WorkoutExerciseDTO;
import com.calorielog.module.training.plan.dto.WorkoutPlanDTO;
import com.calorielog.module.training.plan.entity.WorkoutPlan;
import com.calorielog.module.training.plan.entity.WorkoutPlanExercise;
import com.calorielog.module.training.plan.mapper.WorkoutPlanExerciseMapper;
import com.calorielog.module.training.plan.mapper.WorkoutPlanMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class WorkoutPlanService {

    private final WorkoutPlanMapper planMapper;
    private final WorkoutPlanExerciseMapper planExerciseMapper;

    public List<WorkoutPlanDTO> list(Long userId) {
        List<WorkoutPlan> plans = planMapper.findByUser(userId);
        if (plans.isEmpty()) return List.of();

        List<Long> ids = plans.stream().map(WorkoutPlan::getId).collect(Collectors.toList());
        Map<Long, List<WorkoutPlanExercise>> byPlan = planExerciseMapper.findByPlanIds(ids).stream()
                .collect(Collectors.groupingBy(WorkoutPlanExercise::getPlanId));
        return plans.stream()
                .map(p -> toDTO(p, byPlan.getOrDefault(p.getId(), List.of())))
                .collect(Collectors.toList());
    }

    public WorkoutPlanDTO get(Long userId, Long id) {
        WorkoutPlan p = planMapper.selectById(id);
        if (p == null) throw new BizException(ErrorCode.PLAN_NOT_FOUND);
        if (!p.getUserId().equals(userId)) throw new BizException(ErrorCode.PLAN_NO_PERMISSION);
        return toDTO(p, planExerciseMapper.findByPlan(id));
    }

    @Transactional
    public WorkoutPlanDTO create(Long userId, SavePlanRequest req) {
        WorkoutPlan p = new WorkoutPlan();
        // id auto-generated by DB (BIGSERIAL)
        p.setUserId(userId);
        p.setName(req.getName());
        p.setDescription(req.getDescription());
        p.setType(req.getType() != null ? req.getType() : "strength");
        p.setEstimatedDuration(req.getEstimatedDuration());
        p.setIsTemplate(Boolean.TRUE.equals(req.getIsTemplate()));
        planMapper.insert(p);

        saveExercises(p.getId(), req.getExercises());
        return get(userId, p.getId());
    }

    @Transactional
    public WorkoutPlanDTO update(Long userId, Long id, SavePlanRequest req) {
        WorkoutPlan p = planMapper.selectById(id);
        if (p == null) throw new BizException(ErrorCode.PLAN_NOT_FOUND);
        if (!p.getUserId().equals(userId)) throw new BizException(ErrorCode.PLAN_NO_PERMISSION);

        if (req.getName() != null) p.setName(req.getName());
        if (req.getDescription() != null) p.setDescription(req.getDescription());
        if (req.getType() != null) p.setType(req.getType());
        if (req.getEstimatedDuration() != null) p.setEstimatedDuration(req.getEstimatedDuration());
        if (req.getIsTemplate() != null) p.setIsTemplate(req.getIsTemplate());
        planMapper.updateById(p);

        if (req.getExercises() != null) {
            planExerciseMapper.deleteByPlan(id);
            saveExercises(id, req.getExercises());
        }
        return get(userId, id);
    }

    @Transactional
    public void delete(Long userId, Long id) {
        WorkoutPlan p = planMapper.selectById(id);
        if (p == null) throw new BizException(ErrorCode.PLAN_NOT_FOUND);
        if (!p.getUserId().equals(userId)) throw new BizException(ErrorCode.PLAN_NO_PERMISSION);
        planMapper.deleteById(id); // 逻辑删除
    }

    private void saveExercises(Long planId, List<WorkoutExerciseDTO> items) {
        if (items == null) return;
        int order = 0;
        for (WorkoutExerciseDTO dto : items) {
            WorkoutPlanExercise e = new WorkoutPlanExercise();
            e.setPlanId(planId);
            e.setExerciseId(dto.getExerciseId());
            e.setSets(dto.getSets() != null ? dto.getSets() : 3);
            e.setReps(dto.getReps());
            e.setWeight(dto.getWeight());
            e.setRestSeconds(dto.getRestSeconds() != null ? dto.getRestSeconds() : 60);
            e.setNotes(dto.getNotes());
            e.setSortOrder(dto.getOrder() != null ? dto.getOrder() : order++);
            planExerciseMapper.insert(e);
        }
    }

    private WorkoutPlanDTO toDTO(WorkoutPlan p, List<WorkoutPlanExercise> exs) {
        WorkoutPlanDTO d = new WorkoutPlanDTO();
        d.setId(p.getId());
        d.setName(p.getName());
        d.setDescription(p.getDescription());
        d.setType(p.getType());
        d.setEstimatedDuration(p.getEstimatedDuration());
        d.setIsTemplate(Boolean.TRUE.equals(p.getIsTemplate()));
        d.setCreatedAt(p.getCreatedAt());
        d.setUpdatedAt(p.getUpdatedAt());

        List<WorkoutExerciseDTO> items = new ArrayList<>();
        for (WorkoutPlanExercise e : exs) {
            WorkoutExerciseDTO x = new WorkoutExerciseDTO();
            x.setExerciseId(e.getExerciseId());
            x.setSets(e.getSets());
            x.setReps(e.getReps());
            x.setWeight(e.getWeight());
            x.setRestSeconds(e.getRestSeconds());
            x.setNotes(e.getNotes());
            x.setOrder(e.getSortOrder());
            items.add(x);
        }
        d.setExercises(items);
        return d;
    }

}
