package com.calorielog.module.training.exercise.service;

import com.calorielog.common.exception.BizException;
import com.calorielog.common.exception.ErrorCode;
import com.calorielog.module.training.exercise.dto.ExerciseDTO;
import com.calorielog.module.training.exercise.dto.SaveExerciseRequest;
import com.calorielog.module.strength.entity.Exercise;
import com.calorielog.module.strength.mapper.ExerciseMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service("trainingExerciseService")
@RequiredArgsConstructor
public class ExerciseService {

    private final ExerciseMapper exerciseMapper;

    public List<ExerciseDTO> list(Long userId, boolean popularOnly) {
        return exerciseMapper.findVisibleToUser(userId, popularOnly).stream()
                .map(this::toDTO).collect(Collectors.toList());
    }

    public List<ExerciseDTO> search(Long userId, String query, String category,
                                    boolean popularOnly, int limit) {
        String q = query == null ? "" : query.trim();
        String c = category == null ? "" : category.trim();
        int lim = Math.max(1, Math.min(limit <= 0 ? 100 : limit, 200));
        return exerciseMapper.search(userId, q, c, popularOnly, lim).stream()
                .map(this::toDTO).collect(Collectors.toList());
    }

    public ExerciseDTO get(Long userId, Long id) {
        Exercise e = exerciseMapper.selectById(id);
        if (e == null) throw new BizException(ErrorCode.EXERCISE_NOT_FOUND);
        if (e.getCreatedBy() != null && !e.getCreatedBy().equals(userId)) {
            throw new BizException(ErrorCode.EXERCISE_NO_PERMISSION);
        }
        return toDTO(e);
    }

    public ExerciseDTO create(Long userId, SaveExerciseRequest req) {
        Exercise e = new Exercise();
        // id auto-generated by DB (BIGSERIAL)
        e.setCreatedBy(userId);
        e.setName(req.getName());
        e.setCategory(req.getCategory());
        e.setBodyPart(bodyPartOf(req.getCategory()));
        e.setPrimaryMuscles(joinMuscles(req.getPrimaryMuscles()));
        e.setSecondaryMuscles(joinMuscles(req.getSecondaryMuscles()));
        e.setDifficulty(req.getDifficulty() != null ? req.getDifficulty() : 1);
        e.setInstructions(req.getInstructions());
        e.setTips(req.getTips());
        e.setIsPreset(false);
        e.setIsCustom(true);
        exerciseMapper.insert(e);
        return toDTO(e);
    }

    public ExerciseDTO update(Long userId, Long id, SaveExerciseRequest req) {
        Exercise e = exerciseMapper.selectById(id);
        if (e == null) throw new BizException(ErrorCode.EXERCISE_NOT_FOUND);
        if (e.getCreatedBy() == null || !e.getCreatedBy().equals(userId)) {
            throw new BizException(ErrorCode.EXERCISE_NO_PERMISSION);
        }
        if (req.getName() != null) e.setName(req.getName());
        if (req.getCategory() != null) {
            e.setCategory(req.getCategory());
            e.setBodyPart(bodyPartOf(req.getCategory()));
        }
        if (req.getPrimaryMuscles() != null) e.setPrimaryMuscles(joinMuscles(req.getPrimaryMuscles()));
        if (req.getSecondaryMuscles() != null) e.setSecondaryMuscles(joinMuscles(req.getSecondaryMuscles()));
        if (req.getDifficulty() != null) e.setDifficulty(req.getDifficulty());
        if (req.getInstructions() != null) e.setInstructions(req.getInstructions());
        if (req.getTips() != null) e.setTips(req.getTips());
        exerciseMapper.updateById(e);
        return toDTO(e);
    }

    public void delete(Long userId, Long id) {
        Exercise e = exerciseMapper.selectById(id);
        if (e == null) throw new BizException(ErrorCode.EXERCISE_NOT_FOUND);
        if (e.getCreatedBy() == null || !e.getCreatedBy().equals(userId)) {
            throw new BizException(ErrorCode.EXERCISE_NO_PERMISSION);
        }
        exerciseMapper.deleteById(id);
    }

    public ExerciseDTO toDTO(Exercise e) {
        ExerciseDTO d = new ExerciseDTO();
        d.setId(e.getId());
        d.setName(e.getName());
        d.setCategory(e.getCategory());
        d.setBodyPart(e.getBodyPart());
        d.setPrimaryMuscles(splitMuscles(e.getPrimaryMuscles()));
        d.setSecondaryMuscles(splitMuscles(e.getSecondaryMuscles()));
        d.setDifficulty(e.getDifficulty());
        d.setInstructions(e.getInstructions());
        d.setTips(e.getTips());
        d.setIsCustom(Boolean.TRUE.equals(e.getIsCustom()));
        d.setIsPopular(Boolean.TRUE.equals(e.getIsPopular()));
        d.setImageUrl(e.getImageUrl());
        d.setCreatedAt(e.getCreatedAt());
        d.setUpdatedAt(e.getUpdatedAt());
        return d;
    }

    private static String joinMuscles(List<String> muscles) {
        if (muscles == null || muscles.isEmpty()) return "";
        return String.join(",", muscles);
    }

    private static List<String> splitMuscles(String csv) {
        if (csv == null || csv.isBlank()) return List.of();
        return Arrays.stream(csv.split(","))
                .map(String::trim)
                .filter(s -> !s.isEmpty())
                .collect(Collectors.toList());
    }

    /** 英文 category 反推中文 body_part（与 V9 迁移逻辑保持一致） */
    private static final Map<String, String> CATEGORY_TO_BODYPART = Map.of(
            "chest", "胸部",
            "back", "背部",
            "legs", "腿部",
            "shoulders", "肩部",
            "arms", "手臂",
            "core", "核心",
            "cardio", "有氧"
    );

    public static String bodyPartOf(String category) {
        if (category == null) return "其他";
        return CATEGORY_TO_BODYPART.getOrDefault(category, "其他");
    }
}
